# Generated by Django 5.1.6 on 2025-02-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_administrators'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parketuser',
            options={'verbose_name': 'Parket User', 'verbose_name_plural': 'Parket Users'},
        ),
        migrations.AlterField(
            model_name='parketuser',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parket_users', to='clients.client'),
        ),
    ]
