# Generated by Django 5.1.6 on 2025-02-21 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('administrators', models.ManyToManyField(blank=True, help_text='Users who can manage parking users for this client', related_name='administered_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
