# Generated by Django 5.1.6 on 2025-02-21 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='administrators',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage parket users for this client', related_name='administered_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
